# frozen_string_literal: true

source 'https://rubygems.org'

group :cli do
  gem 'rake'
end

group :testng do
  gem 'rack-test'
  gem 'rspec', '~> 3.0'
  gem 'test-unit'
end

group :lsp do
  gem 'rubocop'
  gem 'rubocop-packaging'
  gem 'rubocop-performance'
  gem 'rubocop-rspec'
  gem 'rubocop-shopify'
  gem 'rubocop-thread_safety'
  gem 'ruby-lsp'
end
